# cd ./conf
# set -a
# source .env 

version: '2'
services:
  ansible_server:
    build: 
      context: ./
      dockerfile: Dockerfile-ansible
      args:
        SSH_ANSIBLE_USER: ${SSH_ANSIBLE_USER}
        SSH_ANSIBLE_PASS: ${SSH_ANSIBLE_PASS}
    hostname: ansible-server-local
    container_name: ansible-server
    extra_hosts:
      - "apache-local-1:172.1.0.20"
      - "apache-local-2:172.1.0.30"
    networks:
      ansible:
        ipv4_address: 172.1.0.10
  
  apache_1:
    build: 
      context: ./
      dockerfile: Dockerfile-apache
      args:
        SSH_ANSIBLE_USER: ${SSH_ANSIBLE_USER}
        SSH_ANSIBLE_PASS: ${SSH_ANSIBLE_PASS}
    hostname: apache-local-1
    container_name: apache-server-1
    ports:
      - "801:80"
    networks:
      ansible:
        ipv4_address: 172.1.0.20

  apache_2:
    build: 
      context: ./
      dockerfile: Dockerfile-apache
      args:
        SSH_ANSIBLE_USER: ${SSH_ANSIBLE_USER}
        SSH_ANSIBLE_PASS: ${SSH_ANSIBLE_PASS}
    hostname: apache-local-2
    container_name: apache-server-2
    ports:
      - "802:80"
    networks:
      ansible:
        ipv4_address: 172.1.0.30

networks:
  ansible:
    ipam:
      config:
      - subnet: 172.1.0.0/24

