# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  
  config.vm.define "c01" do |c1|
    c1.vm.provision "shell", inline: <<-SHELL
      useradd -m -s /bin/bash -U ansiblesrv -u 666 --groups wheel
      cp -pr /home/vagrant/.ssh /home/ansiblesrv/
      chown -R ansiblesrv:ansiblesrv /home/ansiblesrv
      echo "%ansiblesrv ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/ansiblesrv
      sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
      systemctl restart sshd
      echo "ansiblesrv" | passwd --stdin ansiblesrv
      SHELL
    c1.vm.box = "centos/7"
    c1.vm.hostname = "c01"
    c1.vm.network "private_network", ip: "192.168.57.51"
    c1.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
    end
  end

  config.vm.define "c02" do |c2|
    c2.vm.provision "shell", inline: <<-SHELL
      useradd -m -s /bin/bash -U ansiblesrv -u 666 --groups wheel
      cp -pr /home/vagrant/.ssh /home/ansiblesrv/
      chown -R ansiblesrv:ansiblesrv /home/ansiblesrv
      echo "%ansiblesrv ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/ansiblesrv
      sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
      systemctl restart sshd
      echo "ansiblesrv" | passwd --stdin ansiblesrv
      SHELL
    c2.vm.box = "centos/7"
    c2.vm.hostname = "c02"
    c2.vm.network "private_network", ip: "192.168.57.52"
    c2.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
    end
  end

  config.vm.define "d03" do |c3|
    c3.vm.provision "shell", inline: <<-SHELL
      useradd -m -s /bin/bash -U ansiblesrv -u 666 --groups sudo
      cp -pr /home/vagrant/.ssh /home/ansiblesrv/
      chown -R ansiblesrv:ansiblesrv /home/ansiblesrv
      echo "%ansiblesrv ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/ansiblesrv
      sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
      service ssh restart
      echo -e "ansiblesrv\nansiblesrv" | passwd ansiblesrv
      SHELL
    c3.vm.synced_folder '.', '/vagrant', :disabled => true
    c3.vm.box = "debian/jessie64"
    c3.vm.hostname = "d03"
    c3.vm.network "private_network", ip: "192.168.57.53"
    c3.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
    end
  end


end




