FROM ubuntu:19.04

MAINTAINER Grzegorz Boltuc
ARG DEBIAN_FRONTEND=noninteractive

#ARG to creating user with sudo access
ARG SSH_ANSIBLE_USER
ARG SSH_ANSIBLE_PASS

# Install apache, openssh-server for debugging the container.
RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get -y install vim apache2 openssh-server sudo iputils-ping \
    && rm -rf /var/lib/apt/lists/*

# Enable apache mods.
RUN a2enmod rewrite

# Create starting user
COPY ./conf/user.sh /usr/local/bin/user.sh
RUN chmod +x /usr/local/bin/user.sh
RUN /usr/local/bin/user.sh

# Manually set up the apache environment variables
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_PID_FILE /var/run/apache2.pid

# Update the default apache site with the config we created.
ADD ./conf/apache-config.conf /etc/apache2/sites-enabled/000-default.conf

# Expose apache.
EXPOSE 80

# Sudo user 
RUN echo "aido	ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers


#Start SSH and Apache when container is up and running
COPY ./conf/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD tail -f /dev/null


