FROM ubuntu:19.04

MAINTAINER Grzegorz Boltuc

#ARG to creating user with sudo access
ARG SSH_ANSIBLE_USER
ARG SSH_ANSIBLE_PASS

#Install all components to Ansible
RUN apt-get -y update \
    && echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main" >> /etc/apt/sources.list \
    && apt-get install -y gnupg2 \ 
    && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
    
# Install SSH and Ansible.
RUN apt-get -y update \
    && apt-get install -y openssh-server wget sudo iputils-ping vim --no-install-recommends  \
    && apt-get install -y ansible \
    && mkdir -p /var/local/projekty/ansible \
    && apt -y install python-pip \
    && pip install jsondiff \
    && rm -rf /var/lib/apt/lists/*

 
#Create starting user
COPY ./conf/user.sh /usr/local/bin/user.sh
RUN chmod +x /usr/local/bin/user.sh
RUN /usr/local/bin/user.sh

#Copy Ansible conf files and playbooks  
COPY . /opt/local/ansible/

COPY inventory/hosts /etc/ansible/hosts

# Define working directory.

RUN echo "aido	ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers

WORKDIR /opt/local/ansible/

#Start SSH when container is up and running
COPY ./conf/entrypoint2.sh /usr/local/bin/entrypoint2.sh
RUN chmod +x /usr/local/bin/entrypoint2.sh

ENTRYPOINT ["/usr/local/bin/entrypoint2.sh"]

CMD tail -f /dev/null


